# Generated by Django 3.0.3 on 2020-06-21 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicusers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='portfolio',
        ),
    ]
